{
 "title": "Nginx Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Nginx - Req/s por Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(nginx_requests[1m])", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Nginx - Bites Send",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_request_bytes_sent_sum[1m])"
    }
   ]
  },
  {
   "title": "Nginx - Duration time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(nginx_request_duration_bucket) by (instance, le))",
     "legendFormat": "90 Percentil"
    },
    {
     "expr": "histogram_quantile(0.50, sum(nginx_request_duration_bucket) by (instance, le))",
     "legendFormat": "50 Percentil"
    }
   ]
  }
 ]
}